name: Tests

on: [push]

jobs:
  php-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.2, 8.1, 8.0]
        laravel: [11.*, 10.*, 9.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
            -   laravel: 11.*
                testbench: 9.*
            -   laravel: 10.*
                testbench: 8.*
            -   laravel: 9.*
                testbench: 7.*
        exclude:
            -   laravel: 10.*
                php: 8.0
            -   laravel: 11.*
                php: 8.0
            -   laravel: 11.*
                php: 8.1
            -   php: 8.1
                dependency-version: prefer-lowest

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        extensions: mbstring gd

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" --no-update --no-progress
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress

    - name: Execute Unit Tests
      run: composer test