name: Tests

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  php-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.0, 7.4]
        laravel: [9.*, 8.*, 7.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
            -   laravel: 9.*
                testbench: 7.*
            -   laravel: 8.*
                testbench: 6.*
            -   laravel: 7.*
                testbench: 5.*
        exclude:
            -   laravel: 9.*
                php: 7.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        extensions: mbstring gd

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" --no-update --no-progress
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress

    - name: Execute Unit Tests
      run: composer test